apiVersion: v1
kind: Service
metadata:
  labels:
    app: "nextjs-app"
  name: "nextjs-app"
spec:
  ports:
    - port: 3015
      protocol: TCP
      targetPort: 3015
  selector:
    app: "nextjs-app"
  sessionAffinity: None
  type: NodePort